# Example of pipeline which uses runtime parameters
# You are given a list of options to select, or you can use custom mode for choosing multiple options.
# By default all options are selected

parameters:
- name: Select_Services
  type: string
  values:
    - Build_All_Services
    - Service1
    - Service2
  default: 'Build_All_Services'
- name: custom_choices
  type: object
  default: 
    - Service1
    - Service2
    
trigger: 
  - master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'BUILD STAGE'
  jobs:
  - job: Welcome
    steps:
    - task: CmdLine@2
      displayName: 'Selcet Service to build example'
      inputs:
        script: 'echo Selcet Service to build example'
  - ${{ if contains(parameters.Select_Services, 'Service1') }}:
    - job: Service1
      steps:
      - task: CmdLine@2
        displayName: 'Service1 selected'
        inputs:
          script: 'echo Service1 selected'
  - ${{ if contains(parameters.Select_Services, 'Service2') }}:
    - job: Service2
      steps:
      - task: CmdLine@2
        displayName: 'Service2 selected'
        inputs:
          script: 'echo Service2 selected'
- stage: DeployToTEST
  displayName: 'DEPLOY TO TEST STAGE'
  jobs:
  - job: DeployToTESTJob
    steps:
    - powershell: |
     Write-Host 'Environment: test'
    displayName: 'Set environment: ${{ parameters.Environment }}'
