# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: Service1
  type: boolean
  default: true
- name: Service2
  type: boolean
  default: true
    
trigger: 
  - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Pre-Flight
  variables:
  - group: my-variable-group
  displayName: 'Pre-Flight'
  #condition: and(succeeded(), eq('${{ parameters.Service1 }}', 'true'))
  jobs:
  - job: Do Security Scan
    steps:
    - task: CmdLine@2
      displayName: 'Variable from group $(name)'
      inputs:
        script: 'echo Completed Security Scan'
- stage: Build Service1
  dependsOn: Pre-Flight
  displayName: 'BUILD Service 1'
  - job: Service1
    condition: and(succeeded(), eq('${{ parameters.Service1 }}', 'true'))
    steps:
    - task: CmdLine@2
      displayName: 'Service1 selected'
      inputs:
        script: 'echo Service1 selected'
- stage: Build Service2
  dependsOn: Pre-Flight
  displayName: 'BUILD Service 2'   
  - job: Service2
    condition: and(succeeded(), eq('${{ parameters.Service2 }}', 'true'))
    steps:
    - task: CmdLine@2
      displayName: 'Service2 selected'
      inputs:
        script: 'echo Service2 selected'
- stage: DeployToTEST
  dependsOn: Build Service1
  variables:
  - name: Environment
    value: 'single var'
  - group: my-variable-group2
  displayName: 'DEPLOY'
  jobs:
  - job: DeployToTESTJob
    steps:
    - task: CmdLine@2
      displayName: 'Variable from group2 $(name) $(Environment)'
      inputs:
        script: 'echo Selcet Service to build example'
- stage: DeployToTEST2
  displayName: 'DEPLOY'
  dependsOn: Build Service2
  jobs:
  - job: DeployToTESTJob2
    steps:
    - task: CmdLine@2
      displayName: 'Variable from group3'
      inputs:
        script: 'echo Selcet Service to build example'

