# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: Select Services
  type: string
  values:
    - Custom
    - Service1
    - Service2
  default: 'Custom'
- name: custom_choices
  type: object
  default: 
    - Service1
    - Service2
    
trigger: 
  - master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'BUILD STAGE'
  jobs:
  - ${{ if contains(parameters.configs.convertToJson , 'Service1') }}:
    - job: Service1
      steps:
      - task: CmdLine@2
        displayName: 'Frist Task'
        inputs:
          script: 'echo First task'
  - ${{ if contains(parameters.configs, 'Service2') }}:
    - job: Service2
      steps:
      - task: CmdLine@2
        displayName: 'Second task'
        inputs:
          script: 'echo Second task'
- stage: DeployToTEST
  displayName: 'DEPLOY TO TEST STAGE'
  jobs:
  - job: DeployToTESTJob
    steps:
    - script: echo "hello from stage2"
    displayName: 'stage 2'
