# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
- name: Service1
  type: boolean
  default: true
- name: Service2
  type: boolean
  default: true
  
variables:
- group: my-variable-group
    
trigger: 
  - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: 'BUILD STAGE'
  condition: and(succeeded(), eq('${{ parameters.Service1 }}', 'true'))
  jobs:
  - job: Welcome
    steps:
    - task: CmdLine@2
      displayName: 'Variable from group $(name)'
      inputs:
        script: 'echo Selcet Service to build example'
  - job: Service1
    steps:
    - task: CmdLine@2
      displayName: 'Service1 selected'
      inputs:
        script: 'echo Service1 selected'
  - job: Service2
    steps:
    - task: CmdLine@2
      displayName: 'Service2 selected'
      inputs:
        script: 'echo Service2 selected'
- stage: DeployToTEST
  displayName: 'DEPLOY TO TEST STAGE'
  jobs:
  - job: DeployToTESTJob
    steps:
    - script: echo "hello from stage2"
